### ISSUE TITLE
docker ps hangs

### ISSUE THREAD

**Issue by crawford** [coreos/bugs#1654]
# Issue Report #

### CoreOS Version ###

1185.3.0

### Environment ###

AWS and GCE confirmed. Likely all environments.

### Expected Behavior ###

`docker ps` properly returns the list of running containers.

### Actual Behavior ###

`docker ps` eventually hangs (not sure which conditions cause it yet).

### Reproduction Steps ###

In @matti's case:

```
$ docker ps -n 17
# works

$ docker ps -n 18
# hangs
```

### Other Information ###

strace:
```
$ strace -s  128 docker ps -n 18
clock_gettime(CLOCK_MONOTONIC, {484793, 504192514}) = 0
futex(0xc820064108, FUTEX_WAKE, 1)      = 1
read(5, 0xc820400000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
write(5, "GET /v1.23/containers/json?limit=18 HTTP/1.1\r\nHost: \r\nUser-Agent: Docker-Client/1.11.2 (linux)\r\n\r\n", 98) = 98
futex(0xc820064108, FUTEX_WAKE, 1)      = 1
futex(0x22509c8, FUTEX_WAIT, 0, NULL
```

**Comment by crawford** [comment]
@chancez pointed out that https://github.com/docker/docker/issues/13885 and https://github.com/docker/libnetwork/pull/1507 might be related.

**Comment by matti** [comment]
We run 5 machines and get this hang ~weekly (for the last 3 months). Is there anything we could run on the machines when the hang happens again?

**Comment by matti** [comment]
machines are 8CPU/30gb.

During the last hang we were able to start new containers while `docker ps` was hanging.

**Comment by Jwpe** [comment]
I am also experiencing this issue with the following setup: 

**CoreOS Version: 1185.3.0**
**Docker Server Version: 1.11.2**

Not only does `docker ps` hang, but `docker-compose` commands fail with the following error message: 

```bash
Nov 10 10:59:20 <aws_dns>.eu-west-1.compute.internal docker-compose[5872]: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
Nov 10 10:59:20 <aws_dns>.eu-west-1.compute.internal docker-compose[5872]: If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

In the Docker `service` logs these are the only errors I can see:

```
Nov 10 09:38:36 <aws_dns>.eu-west-1.compute.internal dockerd[972]: time="2016-11-10T09:38:36.701843769Z" level=error msg="attach: stdout: write unix /var/run/docker.sock->@: write: broken pipe"
Nov 10 09:38:36 <aws_dns>.eu-west-1.compute.internal dockerd[972]: time="2016-11-10T09:38:36.704819504Z" level=error msg="attach: stderr: write unix /var/run/docker.sock->@: write: broken pipe"
```

**Comment by matti** [comment]
@Jwpe when this happens again, try `docker ps -n 1`, `docker ps -n 2` ... until it hangs just to verify that the symptoms are the same.

`docker-compose` uses the same HTTP api so it will hang as well.

**Comment by Jwpe** [comment]
@matti thanks for the tip, will do!

**Comment by Jwpe** [comment]
@matti for me `docker ps -n 3` works correctly, but `docker ps -n 4` hangs...

**Comment by matti** [comment]
@Jwpe (or anyone else reading this) -- please send SIGUSR1 to the docker daemon process and paste in the logs.

**Comment by Jwpe** [comment]
@matti I get a huge goroutine stack dump on sending that signal:
```
ps -C docker
  PID TTY          TIME CMD
20791 ?        00:00:01 docker
sudo kill -s USR1 20791
journalctl -u docker -n 100
```

```
Nov 10 12:32:08 <aws_dns>.eu-west-1.compute.internal dockerd[20791]: time="2016-11-10T12:32:08.436895136Z" level=info msg="=== BEGIN goroutine stack dump ===\ngoroutine 20 [running]:\n
...
```

**Comment by matti** [comment]
@jwpe yes... please paste the rest of it...

@juhazi over here formatted our stacktrace here: https://gist.github.com/juhazi/fbf22602561b719e9480f8be4f8a4740

**Comment by matti** [comment]
and for the record: this time all daemon API's were jammed:

```
getpeername(5, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, [23]) = 0
futex(0xc820024d08, FUTEX_WAKE, 1)      = 1
read(5, 0xc8203d6000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
write(5, "GET /v1.23/containers/json HTTP/1.1\r\nHost: \r\nUser-Agent: Docker-Client/1.11.2 (linux)\r\n\r\n", 89) = 89
futex(0xc820024d08, FUTEX_WAKE, 1)      = 1
futex(0x22509c8, FUTEX_WAIT, 0, NULL
```

**Comment by basvdlei** [comment]
We are also seeing this behavior on some 1185.3.0 nodes where we are using systemd units with the `docker kill`, `docker rm`, `docker pull` ExecStartPre's as described [here](https://coreos.com/docs/launching-containers/launching/getting-started-with-systemd/).

Here are some goroutine stack dump's of 3 different machines that had the issue that `docker ps` didn't respond unless given a lower `-n` value.
- [node1-20161110.txt](https://github.com/coreos/bugs/files/583839/node1-20161110.txt)
- [node2-20161110.txt](https://github.com/coreos/bugs/files/583838/node2-20161110.txt)
- [node3-20161110.txt](https://github.com/coreos/bugs/files/583837/node3-20161110.txt)

In our case the units also created the following error messages:
```
Handler for POST /v1.23/containers/create returned error: Conflict. The name \"/xxxxxxxxxxx\" is already in use by container 0bf826dafe929711c98d65fa812ed75c4086dc3075e1c148fd1ebfd5c28b0544. You have to remove (or rename) that container to be able to reuse that name."
Handler for POST /v1.23/containers/xxxxxxxxxxx/stop returned error: No such container: xxxxxxxxxxx"
Handler for POST /v1.23/containers/xxxxxxxxxxx/kill returned error: Cannot kill container xxxxxxxxxxx: No such container: xxxxxxxxxxx"
Handler for DELETE /v1.23/containers/xxxxxxxxxxx returned error: No such container: xxxxxxxxxxx"
```

Even though the stop/kill/rm said the container was not there. Which looks a lot like https://github.com/docker/docker/issues/21198 which might be related

Just to be complete, we are also running cadvisor and a custom container that calls list containers about every 5min.

**Comment by matti** [comment]
We are also running cadvisor (as the cluster runs http://www.kontena.io)

**Comment by Tomdarkness** [comment]
Having same issue, here are the logs: https://gist.github.com/anonymous/0ad15cacc028c38ff7759abba7ace198

**Comment by bkleef** [comment]
Same here. Let me know if you need more logs, happy to help.

```
$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:
 OS/Arch:      linux/amd64
```

```
$ uname -a
Linux adrienzoon-mailing.profects.com 4.7.3-coreos-r2 #1 SMP Tue Nov 1 01:38:43 UTC 2016 x86_64 Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz GenuineIntel GNU/Linux
```

```
 cat /etc/lsb-release
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=1185.3.0
DISTRIB_CODENAME="MoreOS"
DISTRIB_DESCRIPTION="CoreOS 1185.3.0 (MoreOS)"
```

**Comment by bkleef** [comment]
I've updated CoreOS 1185.3.0 to 1192.2.0 (Docker 1.11.2 to 1.12.1). Will keep you guys posted!

**Comment by Jwpe** [comment]
Has anyone had any joy here? I'm seeing this every two or three restarts of my containers, and it's currently limiting my ability to repeatably deploy.

**Comment by victorgp** [comment]
We had to roll back to 1122.3.0 and it is working

Version 1185.3.0 it is not usable, every ~24hours the docker daemon gets unresponsive.

**Comment by matti** [comment]
Daemon jammed again, this time not even `docker ps -n 1` worked.

**Comment by Jwpe** [comment]
@bkleef are you seeing this issue still on 1192.2.0? Thanks!

**Comment by bkleef** [comment]
No.

-- 
 

Profects B.V. <http://www.profects.com/>
Goessestraatweg 19, 4421 AD Kapelle, The Netherlands
info@profects.com 
+31 (0)85 301 2083

**Comment by Raffo** [comment]
@Jwpe It's not fixed for us in 1192.2.0.

**Comment by wallneradam** [comment]
It is related to this Docker issue: https://github.com/docker/docker/issues/13885

I found a workaround until it is fixed: you can use `ctr` from `containerd` instead of `docker exec` or `docker run`. I wrote it in more details in this comment: https://github.com/docker/docker/issues/13885#issuecomment-263650807

**Comment by victorgp** [comment]
I don't think that bug is related, it was opened in Jun 2015 and this started to happen recently with the latests CoreOS versions. If that's the bug, then it should've happened in older CoreOS versions

**Comment by wallneradam** [comment]
@victorgp It is almost sure that it is related if you read all the comments or at least the latest ones. Just it is more often under Docker v1.11.0 and up. Which is only in the latest CoreOS (stable) not the previous one.
Not only `docker ps` hangs, but you cannot start or stop containers as well.

Anyway my suggestion is working for me for about a week. And it was not too hard to rewrite my services, which are needed to run processes or new containers, to `ctr, which is integrated into CoreOS...

**Comment by Jwpe** [comment]
@Raffo I haven't encountered the issue since upgrading to 1192.2.0, but I might just not have recreated the scenario where it occurs yet.

**Comment by philk** [comment]
We're also seeing this on 1185.3.0. At least on the one system it's currently happening on `-n9` works but `-n10` fails. The `ctr` command can communicate with things but this failing docker daemon breaks the kubelet making this a completely failed node.

**Comment by hjacobs** [comment]
We had a hanging `docker ps` as well (https://github.com/docker/docker/issues/28889), we could reproduce it by heavily using `docker exec`. We fixed the issue for us by manually upgrading to Docker 1.13 (https://github.com/zalando-incubator/kubernetes-on-aws/pull/164).

We are now waiting for Docker 1.13 release and inclusion in CoreOS: https://github.com/zalando-incubator/kubernetes-on-aws/issues/167

**Comment by seanknox** [comment]
I was also able to reproduce this issue using https://github.com/crosbymichael/docker-stress on a Kubernetes worker node running CoreOS Stable 1185.3.0.

Running `docker_stress_linux_amd64 -k 3s -c 5  --containers 1000`: 5 concurrent workers creating/deleting containers, max lifetime of containers = 3s, create up to 1000 containers on an m4.large instance on AWS would leave the Docker daemon unresponsive after about three minutes.

Upgraded to CoreOS Beta 1235.1.0 and I haven't been able to reproduce. Whereas running 5 concurrent docker_stress workers would kill CoreOS Stable after a few minutes, I was able to run with 10 and 15 concurrent workers until test completion using CoreOS Beta. 

## CoreOS Stable 1185.3.0
### kernel: 4.7.3
### docker: 1.11.2

## CoreOS Beta 1235.1.0
### kernel: 4.8.6
### docker: 1.12.3

**Comment by mward29** [comment]
Just as an FYI, I'm not entirely sure this is CoreOS specific. We are running into the same issues on CentOS. Its feels more relates to Docker atm but I've been unable to get a dump out of Docker on failure to validate.

**Comment by hjacobs** [comment]
@mward29 yes, it's a Docker bug and fixed in 1.13 (and will be backported to 1.12 AFAIK, see https://github.com/docker/docker/issues/28889) --- still it should be fixed in CoreOS (by upgrading to fixed Docker as soon as it's released).

**Comment by dm0-** [comment]
We are updating to Docker 1.12.4, which contains the upstream fixes for the docker daemon deadlocks (docker/docker#29095, docker/docker#29141).  It will be available in the alpha later this week.  You can reopen this if problems persist.

**Comment by Bekt** [comment]
This can't happening to me at about 10% of the time. For non-alpha releases, I solved this by adding a unit that constantly checks docker version and restarts if it hangs.

```
- name: ping-docker.service
  command: start
  content: |
    [Unit]
    Description=Make sure docker is always running.
    [Service]
    ExecStart=(/usr/bin/timeout 2s docker version > /dev/null) || (/usr/bin/systemctl restart docker)
    Restart=always
    RestartSec=10

```

**Comment by saschaarthur** [comment]
sadly im also running into this problem.

Especially if i use docker logs with a huuuuuuuuge log file.

Its reproducable if i stop the stdout of docker logs, and then docker ps is broken. 

heres docker info:
```

Containers: 51
 Running: 5
 Paused: 0
 Stopped: 46
Images: 33
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 239
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.29 GiB
Name: hetzner1
ID: 4BXL:WX4S:LNAP:4G2Y:HK55:WJCH:4LIV:V44I:RY5B:IDBD:APWF:4DYR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by MartinPyka** [comment]
How do you stop the stdout of docker logs?
Would Love to have reliable Methode to reproduce the error

**Comment by krmayankk** [comment]
@hjacobs i am seeing this on 1.12.6 Is this fixed, if yes in which version ? 

 docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:20:01 2017
 OS/Arch:      linux/amd64


strace for docker ps
```
futex(0xc820062908, FUTEX_WAKE, 1)      = 1
futex(0xc820062908, FUTEX_WAKE, 1)      = 1
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 4
setsockopt(4, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
connect(4, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, 23) = 0
epoll_create1(EPOLL_CLOEXEC)            = 5
epoll_ctl(5, EPOLL_CTL_ADD, 4, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3597498464, u64=140156970301536}}) = 0
getsockname(4, {sa_family=AF_LOCAL, NULL}, [2]) = 0
getpeername(4, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, [23]) = 0
futex(0xc820062908, FUTEX_WAKE, 1)      = 1
read(4, 0xc820349000, 4096)             = -1 EAGAIN (Resource temporarily unavailable)
write(4, "GET /v1.24/containers/json HTTP/"..., 95) = 95
futex(0xc820062d08, FUTEX_WAKE, 1)      = 1
futex(0x132ccc8, FUTEX_WAIT, 0, NULL^CProcess 119740 detached
```

**Comment by piyushkv1** [comment]
I'm also seeing this in docker server version 1.12.6

**Comment by funkydorian** [comment]
sudo systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/run/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs:

**Comment by squeed** [comment]
That seems reasonable; docker is a socket-activated service.

**Comment by osman-masood** [comment]
I'm also seeing that `docker ps` is extremely slow (several minutes) on Ubuntu 16 and Docker 17.06.2. My `strace docker` also has a `Resource Temporarily Unavailable` log, like @krmayankk 's above. While running `docker ps` in a different SSH session, this is what I get:

```
> docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:11 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

```
> sudo systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─50-TasksMax.conf
   Active: active (running) since Thu 2017-10-26 00:54:07 UTC; 37min ago
     Docs: https://docs.docker.com
 Main PID: 17541 (dockerd)
    Tasks: 1027
   Memory: 1.8G
      CPU: 42min 36.434s
   CGroup: /system.slice/docker.service
   ...
```


```
> sudo strace docker ps

futex(0xc42002ed10, FUTEX_WAKE, 1)      = 1
clock_gettime(CLOCK_REALTIME, {1508981345, 126155487}) = 0
clock_gettime(CLOCK_REALTIME, {1508981345, 128569956}) = 0
clock_gettime(CLOCK_MONOTONIC, {260815, 252242458}) = 0
futex(0xc42002ed10, FUTEX_WAKE, 1)      = 1
clock_gettime(CLOCK_REALTIME, {1508981345, 128667068}) = 0
socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 3
setsockopt(3, SOL_SOCKET, SO_BROADCAST, [1], 4) = 0
connect(3, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, 23) = 0
epoll_create1(EPOLL_CLOEXEC)            = 4
epoll_ctl(4, EPOLL_CTL_ADD, 3, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=3766348160, u64=140195793856896}}) = 0
getsockname(3, {sa_family=AF_LOCAL, NULL}, [2]) = 0
getpeername(3, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, [23]) = 0
futex(0xc42002e910, FUTEX_WAKE, 1)      = 1
write(3, "GET /_ping HTTP/1.1\r\nHost: docke"..., 83) = 83
futex(0xc42002f110, FUTEX_WAKE, 1)      = 1
futex(0x15e3310, FUTEX_WAIT, 0, NULL)   = 0
futex(0x15e3310, FUTEX_WAIT, 0, NULL)   = -1 EAGAIN (Resource temporarily unavailable)
futex(0x15e3310, FUTEX_WAIT, 0, NULL)   = 0
futex(0x15e3310, FUTEX_WAIT, 0, NULL
```

Even `sudo service docker restart` takes several minutes to run, but it seems to temporarily fix the problem.

**Comment by ilatypov** [comment]
This is still observed in a RedHat 7.7 with Linux 3.10.0-1062.4.3.el7.x86_64 with `docker-ce-cli-19.03.2-3.el7.x86_64`  and `docker-ce-19.03.2-3.el7.x86_64`.

```
[docker-ce-stable]
name=Docker CE Stable - $basearch
baseurl=https://download.docker.com/linux/centos/7/$basearch/stable
enabled=1
gpgcheck=1
gpgkey=https://download.docker.com/linux/centos/gpg
skip_if_unavailable=1
```

**Comment by lucab** [comment]
This ticket is unfortunately starting to attract spurious follow-ups not related to ContainerLinux. I'm thus going to lock this to prevent further unrelated comments.
