### ISSUE TITLE
Download of coreos vagrant base boxes fails on 'vagrant up'

### ISSUE THREAD

**Issue by f-stibane** [coreos/bugs#2101]
# Issue Report #

## Bug ##
Can't download vagrant base box coreos_production_vagrant_virtualbox.box (stable, beta, alpha)

### Container Linux Version ###
any

### Environment ###
Mac OS X
Vagrant
Virtualbox

### Expected Behavior ###
* base box downloads
* vms get started

### Actual Behavior ###
➜   vagrant up
Installing plugins: vagrant-ignition
Installing the 'vagrant-ignition' plugin. This can take a few minutes...
Fetching: vagrant-share-1.1.9.gem (100%)
Fetching: vagrant-ignition-0.0.3.gem (100%)
Installed the plugin 'vagrant-ignition (0.0.3)'!
Bringing machine 'core-01' up with 'virtualbox' provider...
==> core-01: Box 'coreos-alpha' could not be found. Attempting to find and install...
    core-01: Box Provider: virtualbox
    core-01: Box Version: >= 0
==> core-01: Loading metadata for box 'https://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant_virtualbox.json'
    core-01: URL: https://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant_virtualbox.json
==> core-01: Adding box 'coreos-alpha' (v1492.3.0) for provider: virtualbox
    core-01: Downloading: http://builds.release.core-os.net/alpha/amd64-usr/1492.3.0/coreos_production_vagrant_virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 403 Forbidden

### Reproduction Steps ###
git clone https://github.com/coreos/coreos-vagrant.git
cd coreos-vagrant
vagrant up

### Other Information ###
Tried the other base boxes too (stable, beta) - same error

curl -I http://builds.release.core-os.net/alpha/amd64-usr/1492.3.0/coreos_production_vagrant_virtualbox.box
HTTP/1.1 403 Forbidden
X-GUploader-UploadID: AEnB2UrYLpdrBmaCnruOqXZ3eme6GGvnkaww5TbXKvn09bdFsZRYTuUVvM4ME7g4s06WGataHiKhgUjzFeN6GPNYQw28SGGx1A
Content-Type: application/xml; charset=UTF-8
Content-Length: 290
Date: Fri, 11 Aug 2017 09:40:44 GMT
Expires: Fri, 11 Aug 2017 09:40:44 GMT
Cache-Control: private, max-age=0
Server: UploadServer

**Comment by euank** [comment]
We've updated the metadata to point at the correcrt url (https://alpha.release.core-os.net/amd64-usr/1492.3.0/coreos_production_vagrant_virtualbox.box).
It should be fixed now.

For anyone curious how this happened, we used a slightly different build process for this release, which clearly still has some kinks in it.
Thanks for the heads up.

**Comment by f-stibane** [comment]
Very nice, thank you for the quick fix!

For others with the same original problem, these are working too:
stable: https://stable.release.core-os.net/amd64-usr/current/coreos_production_vagrant.box
beta: https://beta.release.core-os.net/amd64-usr/current/coreos_production_vagrant.box

**Comment by martyk** [comment]
How do I get the correct URL plugged into the "$ vagrant box update" command?

**Comment by iahmad-khan** [comment]
Same problem here

**Comment by pezhore** [comment]
Still having the issue with alpha, beta, and stable channels for coreos_production_vagrant_vmware_fusion.

**Comment by euank** [comment]
We did a round of relases (stable v1409.9.0, beta v1465.5.0, alpha v1492.4.0).

These should have correct vagrant json artifacts in their buckets. `current` is also updated, though it might take a little longer due to caching.

Sorry for the trouble! Again, thanks for the report.
